<?php
declare(strict_types=1);


namespace Era269\Microobject\Example\Domain\Identifier;


use Era269\Microobject\AbstractIdentifier;

class AutogeneratedIdentifier extends AbstractIdentifier
{
    final public static function generate(): static
    {
        return static::create(uniqid());
    }
}
