<?php
declare(strict_types=1);

namespace Era269\Microobject\Example\Domain\Notebook;

use Era269\Microobject\Example\Domain\Identifier\AutogeneratedIdentifier;

final class NotebookId extends AutogeneratedIdentifier
{
    protected function generateId(): string
    {
        return uniqid();
    }
}
